name: movieflix
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

# UI
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.11.0
  flare_flutter: ^3.0.2
  flutter_native_splash: any
  animated_bottom_navigation_bar: ^1.1.0+1
  flutter_svg: ^2.0.2
  transformable_list_view: ^0.3.0
  extended_image: ^7.0.2
  animate_do: ^3.0.2

# Functionality
  flutter_bloc: ^8.1.2
  get_it: ^7.2.0
  http: ^0.13.5
  dartz: ^0.10.1
  equatable: ^2.0.5
  path_provider: ^2.0.13
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.jpeg"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/app_logo.png
  android_gravity: center
  ios_content_mode: center


# The following section is specific to Flutter packages.
flutter:

 uses-material-design: true

 assets:
   - assets/images/
   - assets/images/vectors/
   - assets/animations/

 fonts:
   - family: Poppins
     fonts:
       - asset: assets/fonts/Poppins-Thin.ttf
       - asset: assets/fonts/Poppins-Light.ttf
       - asset: assets/fonts/Poppins-Medium.ttf
       - asset: assets/fonts/Poppins-Regular.ttf
       - asset: assets/fonts/Poppins-Semibold.ttf
       - asset: assets/fonts/Poppins-Bold.ttf